### ISSUE TITLE
Kindly, change the extention of each code file from .txt to .java

### ISSUE THREAD

**Issue by giteshsarvaiya** [giteshsarvaiya/java-oop#1]
You can visit the code files in unit 2, 3, 4, 5 
And change the extention of each file from .txt to .java
Also remove the white spaces in the file name.

**Comment by mhdamaan79** [comment]
Okay, I want to work on this issue. Please assign it to me, and I'll handle it by working on one unit at a time.

**Comment by giteshsarvaiya** [comment]
> Okay, I want to work on this issue. Please assign it to me, and I'll handle it by working on one unit at a time.

Sure, Amaan, assigned to you. 
Create 1 PR after each unit.
